# Generated by Django 3.0.5 on 2020-06-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JGapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=250),
        ),
    ]
