# Generated by Django 3.0.5 on 2020-06-21 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JGapp', '0003_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Password',
            new_name='password',
        ),
    ]
